/**
 * Phosphor re-export shim aliased to lucide-react names.
 * Codemod `from "lucide-react"` → `from "@/lib/icons"` and every JSX
 * call site keeps working. Phosphor's API (`size`, `className`, `weight`)
 * overlaps with Lucide for our use cases.
 */

export {
  ArrowBendUpLeft as Reply,
  ArrowDownLeft,
  ArrowLeft,
  ArrowRight,
  ArrowSquareOut as ExternalLink,
  ArrowUpRight,
  ArrowsClockwise as RefreshCw,
  Bell,
  BookOpen,
  Buildings as Building2,
  Calendar,
  CalendarDots as CalendarDays,
  CalendarPlus,
  CaretDown as ChevronDown,
  CaretLeft as ChevronLeft,
  CaretRight as ChevronRight,
  CaretUp as ChevronUp,
  ChatCircle as MessageCircle,
  Check,
  CheckCircle,
  Checks as CheckCheck,
  CircleNotch as Loader2,
  Clock,
  Copy,
  DownloadSimple as Download,
  Envelope as Mail,
  FileText,
  Flame,
  Globe,
  Kanban,
  Key as KeyRound,
  Lightning as Zap,
  List as LayoutList,
  MagnifyingGlass as Search,
  Minus,
  PaperPlaneTilt as Send,
  Phone,
  PhoneSlash as PhoneOff,
  Plus,
  Prohibit as Ban,
  Question as HelpCircle,
  Repeat,
  Sparkle as Sparkles,
  SquaresFour as LayoutDashboard,
  Trash as Trash2,
  Trophy,
  UploadSimple as Upload,
  User,
  UsersThree as Users,
  VideoCamera as Video,
  Warning as AlertTriangle,
  WarningCircle as AlertCircle,
  X,
  XCircle,

  // Extended set — icons used across dashboards/insights/settings
  ChartBar as BarChart3,
  BellSlash as BellOff,
  Robot as Bot,
  Brain,
  CalendarCheck,
  CheckCircle as CheckCircle2,
  CaretUpDown as ChevronsUpDown,
  Stack as Layers,
  Lightbulb,
  LinkSimple as Link2,
  SignOut as LogOut,
  List as Menu,
  ChatText as MessageSquare,
  Chats as MessageSquarePlus,
  ArrowBendUpLeft as MessageSquareReply,
  Moon,
  PhoneCall,
  Quotes as Quote,
  Gear as Settings,
  Sun,
  Tag,
  Target,
  TestTube,
} from '@phosphor-icons/react';
